In [ ]:
Mod5

In [1]:
#exercise5.1 

import time


In [ ]:
t0=time.time()
vals=[]
for i in 

In [3]:
vals=[i*-1 if i%2==1 else i for i in rance (1,100001))]
print ('runtime:') 

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (799284666.py, line 1)

In [9]:
import numpy as np

In [11]:
randos = np.random.randint(1, 7,10) 

In [12]:
randos

array([4, 1, 3, 3, 3, 5, 2, 5, 5, 1])

In [19]:
ra1 = np.random.randint(10)

In [20]:
type(ra1)

int

In [21]:
ra2=np.random.randint(1,21,5)

In [22]:
type(ra2)

numpy.ndarray

In [26]:
#exercise5.5

from matplotlib.pylot import hist

ModuleNotFoundError: No module named 'matplotlib.pylot'

In [27]:
#exercise5.6

mat=np.random.randn(2,3)

In [28]:
mat

array([[-0.42739765, -0.97575084,  0.87679204],
       [ 0.63482454,  0.23183734, -0.46236737]])

In [29]:
#exercise5.7

mat*2

array([[-0.85479531, -1.95150168,  1.75358408],
       [ 1.26964908,  0.46367467, -0.92473474]])

In [31]:
#exercise5.8
mat+mat

array([[-0.85479531, -1.95150168,  1.75358408],
       [ 1.26964908,  0.46367467, -0.92473474]])

In [35]:
#exercise5.9 matrix of reciprocals
1/mat

array([[-2.33974143, -1.0248518 ,  1.1405213 ],
       [ 1.57523841,  4.31336908, -2.16278237]])

In [40]:
#exercise5.10
shape=(2,4)
z1=np.zeros(shape)
z1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
z2=np.ones(shape)
z2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
#exercise5.11
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
#exercise5.12
x1=np.random.rand(5)

In [49]:
x1

array([0.79177725, 0.57164412, 0.94209468, 0.83994206, 0.38806213])

In [50]:
x1[1:4]

array([0.57164412, 0.94209468, 0.83994206])

In [51]:
x1[1:-1]

array([0.57164412, 0.94209468, 0.83994206])

In [59]:
#exercise5.13
x1[x1>0.15]

array([0.79177725, 0.57164412, 0.94209468, 0.83994206, 0.38806213])

In [60]:
bool_idx=x1>.15

In [61]:
bool_idx

array([ True,  True,  True,  True,  True])

In [64]:
#exercise5.14
x4=np.random.rand(3,3)

In [65]:
x4

array([[0.67346722, 0.87337381, 0.18684846],
       [0.11357579, 0.26671405, 0.37130589],
       [0.44367894, 0.26996047, 0.88361538]])

In [66]:
x4[1:, :-1]

array([[0.11357579, 0.26671405],
       [0.44367894, 0.26996047]])

In [67]:
x4[1:, :2]

array([[0.11357579, 0.26671405],
       [0.44367894, 0.26996047]])